config/routes.rb
Rails.application.routes.draw do
  resources :categories
  get 'pages/home'
  get "about" => "pages#about"
  root to: 'pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :users, only: [:show]
  resources :events
  resources :profiles, only: [:new, :edit, :create, :update]
  resources :photos, only: [:destroy]

  resources :events do
    resources :registrations, only: [:create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_and_belongs_to_many :events

  validates :name, presence: true, uniqueness: true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :categories
  has_many :registrations, dependent: :destroy
  has_many :guests, through: :registrations, source: :user
  has_many :photos

  validates :name, presence: true
  validates :description, presence: true, length: {maximum: 1000}

  def small?
    capacity < 20
  end

  def self.order_by_price
    order(:price)
  end

end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :event

  mount_uploader :image, ImageUploader
end

app/models/profile.rb
class Profile < ApplicationRecord
  
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :bio, presence: true

  def full_name
    "#{first_name} #{last_name}"
  end

  def self.by_initial(letter)
    where("first_name LIKE ?", "#{letter}%").order(:first_name)
  end
end

app/models/registration.rb
class Registration < ApplicationRecord
  belongs_to :user
  belongs_to :event

  validates :guests_count, presence: true

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :events, dependent: :destroy
  has_one :profile
  has_many :registrations, dependent: :destroy
  has_many :registered_events, through: :registrations, source: :event

  def has_profile?
    profile.present? && profile.persisted?
  end

  def full_name
    profile.full_name
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update]
  before_action :authenticate_user!, except: [:show]

  def index
    @events = current_user.events
  end

  def show
    @categories = @event.categories
    @photos = @event.photos
  end

  def new
    @event = current_user.events.build
  end

  def create
    @event = current_user.events.build(event_params)

    if @event.save
      create_images
      redirect_to @event, notice: "Event successfully created"
    else
      render :new
    end
  end

  def edit
    if current_user.id == @event.user.id
      @photos = @event.photos
    else
      redirect_to root_path, notice: "You don't have permission."
    end
  end

  def update
    if @event.update(event_params)
      create_images
      redirect_to @event, notice: "Event successfully updated"
    else
      render :edit
    end
  end

  private
    def set_event
      @event = Event.find(params[:id])
    end

    def event_params
      params.require(:event).permit(:name, :description, :location, :price, :capacity, :includes_food, :includes_drinks, :starts_at, :ends_at, :active, :user, category_ids: [])
    end

    def image_params
      params[:images].present? ? params.require(:images) : []
    end

    def create_images
      image_params.each do |image|
        @event.photos.create(image: image)
      end
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @events = Event.all
  end

  def about
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def destroy
      photo = Photo.find(params[:id])
      @event = photo.event
      if @event.user.id == current_user.id
        photo.destroy

        redirect_to edit_event_path(@event), notice: "Photo successfully removed"
      else
        redirect_to @event, notice: "Cannot delete that photo"
      end
    end
  end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :set_profile, only: [:edit, :update]
  before_action :authenticate_user!

  def new
    @profile = Profile.new
  end

  def create
    @profile = current_user.build_profile(profile_params)

    if @profile.save
      redirect_to edit_profile_path(@profile), notice: "Profile successfully created"
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update(profile_params)
      redirect_to edit_profile_path(@profile), notice: "Profile successfully updated"
    else
      render :edit
    end
  end

  private
    def set_profile
      @profile = current_user.profile
    end

    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :bio)
    end
end

app/controllers/registrations_controller.rb
class RegistrationsController < ApplicationController
  before_action :authenticate_user!

  def create
    @registration = current_user.registrations.create(registration_params)
    redirect_to @registration.event, notice: "Thank you for registering!"
  end

  def total_price
    total_price = @event.price * guests_count
    puts total_price
  end

  private


  def registration_params
    params.require(:registration)
          .permit(:guests_count, :price, :total, :event_id)
          .merge(event_id: params[:event_id])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_for @event, html: { multipart: true } do |f| %>

  <ul>
     <% @event.errors.full_messages.each do |msg| %>
       <li><%= msg %></li>
     <% end %>
  </ul>


  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :location %>
  <%= f.text_field :location %>

  <%= f.label :price %>
  <%= f.number_field :price %>

  <%= f.label :capacity %>
  <%= f.number_field :capacity %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <div class="form-group">
    <%= f.check_box :includes_drinks %> Drinks
  </div>
  <div class="form-group">
    <%= f.check_box :includes_food %> Food
  </div>

  <label>Photos</label>

  <div class="form-group">
    <span class="btn btn-default">
      Upload Photos
      <%= file_field_tag "images[]", type: :file, multiple: true %>
    </span>
  </div>

  <div id="photos">
    <%= render 'photos/list' %>
  </div>

  <%= f.submit (@event.new_record? ? "Create event" : "Update event") %>

<% end %>

app/views/events/edit.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Edit event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/index.html.erb
<!-- Main jumbotron for a primary marketing message or call to action -->
<div class="jumbotron">
  <div class="container">
    <h1>Welcome to Codaisseurup!</h1>
    <p>Find me in app/views/pages/home.html.erb</p>
    <p><a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a></p>
  </div>
</div>


<div class="row">
  <div class="col-md-3">

  </div>
  <div class="col-md-9">
    <div class="panel panel-primary">
      <div class="panel-heading">
        Your Event Listings
      </div>
      <div class="panel-body">

        <% @events.each do |event| %>
        <div class="row">
          <div class="col-md-7">
            <h4><%= event.name %></h4>
          </div>
          <div class="col-md-3 right">
            <%= link_to "View", event, class: "btn btn-default" %>
            <%= link_to "Update", edit_event_path(event), class: "btn btn-default" %>
          </div>
        </div>
        <% end %>

      </div>
    </div>

    <%= link_to "Add new event", new_event_path, class: "btn btn-primary" %>
  </div>
</div>

app/views/events/new.html.erb
<div class="panel panel-default">
  <div class="panel-heading">
    Add a new event
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/events/show.html.erb
<% if current_user != @event.user %>
  <div class="panel panel-primary">
    <div class="panel-heading">Register for this event</div>

    <div class="panel-body">
      <%= render 'registrations/form' %>
    </div>
  </div>
<% end %>

<div class="panel panel-primary">
  <div class="panel-heading"><%= @event.name %></div>

  <div class="panel-body">

    <h4><%= @event.name %></h4>
    <br>

    <p>Location: <%= @event.location %></p>
    <p>Host: <%= @event.user.email %></p>
    <p>Price: <%= @event.price %></p>
    <p>Capacity: <%= @event.capacity %></p>


    <!-- About -->
    <h4>About</h4>
    <p><%= @event.description %></p>

    <!-- Extra Info -->
    <h4>Refreshments</h4>
    <ul class="amenities">
      <li><%= !@event.includes_food ? ("Does not include food").html_safe : "Includes Food" %></li>
      <li><%= !@event.includes_drinks ? ("<Does not include drinks</del>").html_safe : "Includes Drinks" %></li>
    </ul>

    <h4>Categories</h4>
    <% @categories.each do |category| %>
      <span class="label label-success"><%= category.name %></span>
    <% end %>

    <!-- Photos -->
    <h4>Photos</h4>
    <% @event.photos.each do |photo| %>
      <div class="panel panel-default">
        <div class="panel-heading">
          <%= image_tag photo.image.thumbnail %>
        </div>
      </div>
    <% end %>


  </div>

</div>

<%= link_to "Back", events_path, class: "btn btn-default" %>

app/views/photos/_list.html.erb
<% if @photos %>
  <% @photos.each do |photo| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <%= image_tag photo.image.thumbnail %>
      </div>
      <div class="panel-body">
        <%= link_to "Delete", photo, class: "btn btn-default", method: :delete, data: { confirm: "Are you sure?" } %>
      </div>
    </div>
  <% end %>
<% end %>

app/views/profiles/_form.html.erb
<%= form_for @profile do |f| %>
  <% @profile.errors.full_messages.each do |msg| %>
    <p class="alert alert-danger"><%= msg %></p>
  <% end %>

  <div class="form-group">
    <label>First Name</label>
    <%= f.text_field :first_name, placeholder: "First Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Last Name</label>
    <%= f.text_field :last_name, placeholder: "Last Name", class: "form-control" %>
  </div>

  <div class="form-group">
    <label>Bio</label>
    <%= f.text_area :bio, rows: 5, placeholder: "Say something about yourself", class: "form-control" %>
  </div>

  <div class="actions">
    <%= f.submit "Save", class: "btn btn-primary" %>
    <%= link_to "Back", root_path, class: "btn btn-default" %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Edit your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>

app/views/profiles/new.html.erb
<div class="panel panel-primary">
  <div class="panel-heading">
    Create your profile
  </div>

  <div class="panel-body">
    <%= render 'form' %>
  </div>
</div>